import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const modules = [
  { code: 'CS201', name: 'Algorithms & Complexity', progress: 84, active: '2 hours ago' },
  { code: 'MATH301', name: 'Linear Algebra & Statistics', progress: 62, active: 'Yesterday' },
  { code: 'BIO105', name: 'Molecular Physiology', progress: 95, active: '3 days ago' },
];
const questions = [
  'Suppose we are using a standard greedy interval partitioning method to schedule classes. What is the guaranteed optimal relationship bound if classes are ordered purely by academic level instead of start times?',
  'Which property guarantees that a dynamic programming solution can be assembled from optimal solutions to smaller subproblems?',
  'What is the runtime of Floyd-Warshall all-pairs shortest path algorithm on a graph with V vertices?',
];
const answers = [
  ['It is bound by a constant factor of O(d) where d represents the depth of the optimal partition.', 'No logical optimal bound can be guaranteed without checking the specific chronological start overlaps.', 'The scheduling matches the performance of the earliest-deadline-first heuristic perfectly.', 'The partition collapses to a single continuous sequence without optimal depth guarantees.'],
  ['The optimal substructure property.', 'A random greedy choice.', 'The adjacency matrix density.', 'The number of graph vertices only.'],
  ['O(V)', 'O(V²)', 'O(V³)', 'O(2V)'],
];

function Brand() { return <span className="brand">FastLearnee <b>PRO</b></span>; }
function Button({ children, kind = 'primary', onClick, className = '', disabled = false }) { return <button type="button" disabled={disabled} className={`button ${kind} ${className}`} onClick={onClick}>{children}</button>; }
function Badge({ children, tone = 'green' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Ring({ value, red = false }) { return <span className={`ring ${red ? 'red' : ''}`}><b>{value}%</b></span>; }
function Title({ children, subtitle, action }) { return <div className="title-row"><div><h1>{children}</h1>{subtitle && <p>{subtitle}</p>}</div>{action}</div>; }

function Header({ setScreen, setSearchOpen, admin = false }) {
  return <header className="topbar">
    <button className="brand-button" type="button" onClick={() => setScreen('dashboard')}><Brand /></button><span className="divider" />
    <button className="uni-select" type="button" onClick={() => setSearchOpen('Oxford University courses')}>Oxford University⌄</button>
    <button className="search" type="button" onClick={() => setSearchOpen('Search results')} aria-label="Search modules"><span>⌕</span><span>Search modules, past papers, notes...</span></button>
    <span className="term">▣ &nbsp; MT Term 2026</span><span className="avatar">EW</span><b className="user-name">Emma Wilson</b>{admin && <Badge tone="dark">ADMIN</Badge>}
  </header>;
}
function Page({ children, screen, setScreen, admin = false }) {
  const [notice, setNotice] = useState('');
  const [searchOpen, setSearchOpen] = useState('');
  return <><Header setScreen={setScreen} setSearchOpen={setSearchOpen} admin={admin} /><main className="page">{children}</main>
    {notice && <button className="toast" type="button" onClick={() => setNotice('')}>{notice} ×</button>}
    {searchOpen && <div className="modal-backdrop" onClick={() => setSearchOpen('')}><section className="modal" onClick={(event) => event.stopPropagation()}><h2>{searchOpen}</h2><p>Search and account discovery will connect to your university workspace.</p><Button onClick={() => setSearchOpen('')}>Close</Button></section></div>}
    <nav className="screen-nav" aria-label="Application screens">{['dashboard', 'quiz', 'exam', 'evaluation', 'diagnostics', 'revision', 'admin', 'materials'].map((item) => <button type="button" key={item} className={screen === item ? 'selected' : ''} onClick={() => setScreen(item)}>{item}</button>)}</nav>
  </>;
}

function Dashboard({ setScreen }) {
  const [attempt, setAttempt] = useState(true);
  return <Page screen="dashboard" setScreen={setScreen}><Title subtitle="Your custom study templates are synched with the latest board blueprints." action={<span className="pill">Syllabus Coverage: 78% Completed</span>}>Continue where you left off</Title>
    <div className="module-grid">{modules.map((module) => <article className="module-card" key={module.code}><small>{module.code}</small><h2>{module.name}</h2><Ring value={module.progress} /><hr /><p>Last active: {module.active}</p><div className="card-actions"><Button onClick={() => setScreen('quiz')}>Generate Quiz</Button><Button kind="outline" onClick={() => setScreen('revision')}>Revision Sheet</Button></div></article>)}</div>
    <p className="section-label">IN-PROGRESS EXAMINATION</p>{attempt ? <article className="exam-resume lined"><div><h2>CS201: Mock Midterm Exam <Badge tone="yellow">Adaptive Testing</Badge></h2><p>Dissected from last term's computer science board papers. Timer remains at 18:40. Real syllabus weighting rules are applied.</p><div className="progress"><span style={{ width: '56%' }} /></div><Button onClick={() => setScreen('exam')}>Resume Quiz Attempt</Button> <Button kind="outline" onClick={() => setAttempt(false)}>Discard Attempt</Button></div><b>14 / 25 Questions Completed</b></article> : <article className="empty-inline"><b>No active exam attempts.</b><Button onClick={() => setScreen('quiz')}>Create a quiz</Button></article>}
    <p className="section-label">RECENTLY GRADED SHEETS</p><div className="graded-grid">{['Dynamic Programming Drill #4', 'Complex Matrices & Eigenvectors', 'Synaptic Transmission Mastery'].map((name, index) => <article className="graded-card" key={name}><small>Submitted Aug {28 - index * 3}</small><h3>{name}</h3><button type="button" className="link-button" onClick={() => setScreen('evaluation')}>View correction sheet →</button><Ring value={[9, 8, 10][index]} red /></article>)}</div>
  </Page>;
}

function Quiz({ setScreen }) {
  const [topics, setTopics] = useState([0, 1, 3]); const [count, setCount] = useState(15); const [format, setFormat] = useState('Multiple Choice (MCQ)'); const [module, setModule] = useState(0); const topicNames = ['Dynamic Programming Drill', 'Graph Traversals (DFS/BFS)', 'NP-Completeness Proofs', 'Asymptotic Complexity Bounds', 'Greedy Interval Scheduling', 'Divide and Conquer Masters Theory'];
  return <Page screen="quiz" setScreen={setScreen}><Title subtitle="Configure your criteria below to generate highly adaptive testing aligned with your syllabus structure." action={<span className="pill">Adaptive Prep Standard: MT Term 2026</span>}>Generate Custom Exam Quiz</Title>
    <section className="paper-panel quiz-panel"><div className="form-heading"><div><small>MODULE TARGET SELECTION</small><h2>{modules[module].code}: {modules[module].name}</h2></div><Button kind="outline" onClick={() => setModule((module + 1) % modules.length)}>Change Module⌄</Button></div><hr /><small>SELECT SYLLABUS TOPICS</small><div className="topic-grid">{topicNames.map((topic, index) => <button type="button" className={topics.includes(index) ? 'topic checked' : 'topic'} onClick={() => setTopics(topics.includes(index) ? topics.filter((item) => item !== index) : [...topics, index])} key={topic}>{topics.includes(index) ? '☑' : '□'} {topic}</button>)}</div><hr /><div className="settings-row"><div><small>QUESTION COUNT</small><div className="choice-row">{[10, 15, 20, 25].map((value) => <button type="button" className={count === value ? 'choice active' : 'choice'} onClick={() => setCount(value)} key={value}>{value}</button>)}</div></div><div><small>DIFFICULTY MIX (%)</small><div className="difficulty"><span>● &nbsp; Easy: &nbsp; <b>30%</b></span><span>● &nbsp; Medium: &nbsp; <b>50%</b></span><span>● &nbsp; Hard: &nbsp; <b>20%</b></span></div></div></div><hr /><div className="settings-row"><div><small>BLOOM'S TAXONOMY LEVELS</small><div className="chips">{['Remember', 'Understand', 'Apply', 'Analyse', 'Evaluate', 'Create'].map((item, index) => <span className={index < 4 ? 'chip active' : 'chip'} key={item}>• {item}</span>)}</div></div><div><small>QUESTION FORMATS</small><div className="chips">{['Multiple Choice (MCQ)', 'Short Answer', 'True/False', 'Essay Format'].map((item) => <button type="button" className={format === item ? 'chip active' : 'chip'} onClick={() => setFormat(item)} key={item}>{item}</button>)}</div></div></div><hr /><div className="center"><Button disabled={!topics.length} onClick={() => setScreen('exam')}>Generate {count}-Question Quiz</Button><small>{topics.length} topics selected · {format} · {modules[module].code}</small></div><div className="status-line">✓ &nbsp; Ready to retrieve past-paper patterns and generate balanced questions</div></section>
  </Page>;
}

function Exam({ setScreen }) {
  const [question, setQuestion] = useState(0); const [selected, setSelected] = useState(null); const [flagged, setFlagged] = useState([]); const currentAnswers = answers[question];
  function move(next) { setQuestion(Math.max(0, Math.min(questions.length - 1, next))); setSelected(null); }
  return <Page screen="exam" setScreen={setScreen}><div className="exam-top"><b>CURRENTLY TAKING EXAMINATION &nbsp; | &nbsp; CS201: Algorithms Mock Term</b><span>◷ <strong>18:40 Remaining</strong><br />Question {question + 1} of 15</span></div><div className="exam-layout"><section className="question lined"><small>QUESTION {String(question + 1).padStart(2, '0')} (BLOOM LEVEL: APPLY)</small><h2>{questions[question]}</h2>{currentAnswers.map((answer, index) => <button type="button" className={selected === index ? 'answer selected' : 'answer'} onClick={() => setSelected(index)} key={answer}><b>{String.fromCharCode(65 + index)}.</b> {answer}</button>)}<button type="button" className="flag" onClick={() => setFlagged(flagged.includes(question) ? flagged.filter((item) => item !== question) : [...flagged, question])}>⚑ &nbsp; {flagged.includes(question) ? 'Flagged for grading review' : 'Flag this question for grading review'}</button></section><aside className="palette"><b>EXAMINATION PALETTE</b><p>Monitor your response matrix in real-time.</p><div className="numbers">{Array.from({ length: 15 }, (_, index) => <button type="button" className={index === question ? 'current' : index < question ? 'done' : flagged.includes(index) ? 'flagged' : ''} onClick={() => move(index)} key={index}>{index + 1}</button>)}</div><b>LEGEND KEY</b><p>◼ &nbsp; Answered &amp; Saved</p><p>▢ &nbsp; Flagged for Review</p><p>□ &nbsp; Unanswered / Empty</p></aside></div><div className="exam-actions"><Button kind="outline" disabled={question === 0} onClick={() => move(question - 1)}>← &nbsp; Previous</Button><Button kind="outline" disabled={question === questions.length - 1} onClick={() => move(question + 1)}>Next Question &nbsp; →</Button><Button onClick={() => setScreen('evaluation')}>Submit Mock Quiz</Button></div></Page>;
}

function Evaluation({ setScreen }) { const [filter, setFilter] = useState('All'); const results = [['Define the optimal substructure property of dynamic programming as applied to the Knapsack problem.', 'The knapsack of capacity W can be solved by combining solutions to subproblems of smaller capacities.', 'CORRECT'], ['What is the runtime of Floyd-Warshall all-pairs shortest path algorithm on a graph with V vertices?', 'O(V^2) (too low)', 'INCORRECT'], ['Suppose we are using a standard greedy interval partitioning method to schedule classes.', 'No logical optimal bound can be guaranteed without checking the specific chronological start overlaps.', 'CORRECT']]; const visible = results.filter(([, , status]) => filter === 'All' || status === filter.toUpperCase()); return <Page screen="evaluation" setScreen={setScreen}><Title subtitle="CS201: Algorithms & Complexity Mock Midterm Review" action={<span className="pill">Syllabus Blueprint Verified</span>}>Examination Evaluation</Title><section className="evaluation-summary lined"><div><h2>Performance Analysis</h2><p>Excellent command of Dynamic Programming, but edge-case complexity bounds require targeted revision sheets.</p><b>QUESTIONS &nbsp; <strong>15 Total</strong> &nbsp;&nbsp;&nbsp; CORRECT ANSWERS &nbsp; <strong className="green-text">11 / 15</strong> &nbsp;&nbsp;&nbsp; TIME ELAPSED &nbsp; <strong>21 mins 12s</strong></b></div><Ring value={73} red /></section><div className="filters">FILTER FEEDBACK: {['All', 'Correct', 'Incorrect'].map((item) => <button type="button" className={filter === item ? 'filter active' : 'filter'} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div>{visible.map(([question, answer, status], index) => <article className="feedback-card" key={question}><h3>Question {index + 1} <Badge tone={status === 'CORRECT' ? 'green' : 'red'}>{status}</Badge></h3><p>{question}</p><small>YOUR ANSWER:</small><b className={status === 'CORRECT' ? 'green-text' : 'red-text'}>{answer}</b><div className="explanation"><small>EXPLANATION &amp; BLUEPRINT CORRELATION</small><br />Grounded in computational state board frameworks. Subproblem optimal paths compose the overall optimal recurrence.</div></article>)}<div className="right"><Button onClick={() => setScreen('revision')}>Generate revision sheet from my mistakes</Button></div></Page>; }

function Diagnostics({ setScreen }) { return <Page screen="diagnostics" setScreen={setScreen}><Title subtitle="Track your syllabus mastery and board blueprint coverage in real-time." action={<span className="pill">Overall Pass Probability: 94.2%</span>}>Performance &amp; Diagnostics</Title><div className="stats-grid"><article><small>QUIZZES TAKEN</small><strong>42</strong><b>+8 this week</b></article><article><small>AVERAGE SCORE</small><strong>85%</strong><span>VERIFIED</span></article><article><small>CURRENT STREAK</small><strong>14 <small>days</small></strong><Badge tone="yellow">Active</Badge></article></div><div className="diagnostic-grid"><section className="paper-panel chart"><h2>Mock Performance History</h2><span>Graphite &amp; Red Ink Trace</span><div className="chart-line">65%　 78%　 76%　 85%　 73%　 90%　 88%　 95%</div><div className="chart-axis">Mock 1　　 Mock 2　　 Mock 3　　 Mock 4　　 Mock 5　　 Mock 6　　 Mock 7　　 Final Drill</div></section><section className="paper-panel weak"><small>PRIORITY DIAGNOSTICS</small><h2>Syllabus Weak Spots</h2>{['CS201  Dynamic Programming Edge Cases', 'BIO105  Synaptic Action Potential Potentiation', 'MATH301  Covariance & Statistical Estimators'].map((item) => <p key={item}><b>{item}</b><button type="button" className="link-button" onClick={() => setScreen('quiz')}>Practice this</button><i /></p>)}</section></div><div className="diagnostic-grid bottom"><section className="paper-panel taxonomy"><small>COGNITIVE DEPTH PROFILE</small><h2>Bloom's Taxonomy Performance</h2>{['Remember 92%', 'Understand 85%', 'Apply 78%', 'Analyze 64%', 'Evaluate 45%', 'Create 30%'].map((item, index) => <p key={item}>{index + 1}. {item}<i style={{ width: `${92 - index * 12}%` }} /></p>)}</section><section className="paper-panel empty-state"><span>▢</span><h2>New Syllabus Detected</h2><p>Take your first customizable adaptive quiz to start tracking detailed Bloom and topic diagnostics.</p><Button onClick={() => setScreen('quiz')}>Generate First Quiz</Button></section></div></Page>; }

function Revision({ setScreen }) { const [version, setVersion] = useState('v2.4'); return <Page screen="revision" setScreen={setScreen}><div className="notice">ⓘ &nbsp; Source material has been updated since this sheet was generated <button type="button" onClick={() => setVersion('v2.5')}>Regenerate now</button></div><Title subtitle="Generated from algorithmic past board papers & personal mistake profile." action={<Button kind="outline" onClick={() => setVersion('v2.5')}>Regenerate Sheet</Button>}>CS201 Revision Sheet: Dynamic Programming <small>{version} (Aug 29, 2026)</small></Title><div className="revision-layout"><article className="revision-paper lined"><h2>Core Theorem: Bellman Recurrence</h2><p>The foundational bedrock of dynamic programming lies within the partition of subproblem decisions. To guarantee an optimal overall decision path, any subproblem path must itself represent the mathematically verified local optimum.</p><div className="formula"><small>BELLMAN DYNAMIC PROGRAMMING RECURRENCE</small><b>OPT(i, w) = max( OPT(i-1, w), v_i + OPT(i-1, w - w_i) )</b><span>Where OPT(i, w) represents the optimal value of subset using first i items within total weight allowance w.</span></div><h2>Interval Partitioning vs Start Overlaps</h2><p>Grounded on Oxford computational syllabus guidelines: Ordering interval partitioning purely by non-chronological indexes destroys optimal greedy performance bounds. True optimal depth guarantees demand checking each real chronological start metric.</p></article><aside className="terms"><b>KEY TERMS &amp; BLUEPRINTS</b><p>Essential vocabulary for this syllabus.</p>{[['Optimal Substructure', 'The mathematical property where the optimal solution to an optimization problem contains optimal solutions to subproblems.'], ['Knapsack Decidability', 'Solving allocation boundaries over constrained capacities utilizing precise recurrence indices.'], ['Greedy Interval Depth', 'The minimum number of partition sets required to schedule a collection of chronological intervals.']].map(([term, description]) => <div key={term}><h3>{term}</h3><p>{description}</p></div>)}</aside></div></Page>; }

function Admin({ setScreen }) { const [rows, setRows] = useState(5); const [message, setMessage] = useState(''); return <Page screen="admin" setScreen={setScreen} admin><Title subtitle="Map internal course parameters, upload paper blueprints, and enforce state-board schema validity." action={<><Button kind="outline" onClick={() => setMessage('Schemas exported successfully.')}>Export Schemas</Button> <Button onClick={() => setMessage('New module draft created.')}>Create Module +</Button></>}>Module &amp; Blueprint Administration</Title><section className="upload"><span>♧</span><b>Upload Official Board Blueprint / Syllabus PDF</b><p>Our parser will auto-extract syllabus weightings, Bloom cognitive depths, and past exam models.</p><Button kind="outline" onClick={() => setMessage('Upload picker ready for PDF, JSON, or CSV files.')}>Choose file</Button></section>{message && <p className="form-message">{message}</p>}<section className="admin-table"><div className="table-head">CODE <span>NAME</span><span>STATUS</span><span>PAST PAPERS</span><span>VALIDATION STATUS</span><span>ACTIONS</span></div>{[['CS201', 'Algorithms & Complexity', '14 papers', 'Validated'], ['MATH301', 'Linear Algebra & Statistics', '8 papers', 'Validated'], ['BIO105', 'Molecular Physiology', '11 papers', 'Validating'], ['LIT102', 'Victorian Narrative Prose', '4 papers', 'Not Validated'], ['PHY204', 'Quantum Mechanics & Wave Theory', '19 papers', 'Mismatch Detected']].slice(0, rows).map(([code, name, papers, validation], index) => <div className="table-row" key={code}><b>{code}</b><strong>{name}</strong><Badge tone={index === 3 ? 'light' : 'green'}>{index === 3 ? 'Archived' : 'Active'}</Badge><span>{papers}</span><Badge tone={validation === 'Mismatch Detected' ? 'red' : validation === 'Validating' ? 'yellow' : validation === 'Not Validated' ? 'light' : 'green'}>{validation}</Badge><span><button type="button" className="link-button" onClick={() => setMessage(`${code} is ready to edit.`)}>Edit</button>　<button type="button" className="link-button red-text" onClick={() => setRows(Math.max(0, rows - 1))}>Archive</button></span></div>)}</section></Page>; }

function Materials({ setScreen }) { const [tab, setTab] = useState('Materials'); const [uploaded, setUploaded] = useState(false); return <Page screen="materials" setScreen={setScreen}><aside className="materials-nav"><b>ACADEMIC MODULES</b>{['CS201: Algorithms & Complexity', 'MATH301: Linear Algebra', 'BIO105: Molecular Physiology', 'LIT102: Classical Literature'].map((item, index) => <button type="button" className={index === 0 ? 'active' : ''} key={item}>{item}<Badge tone="light">{[14, 8, 21, 5][index]}</Badge></button>)}</aside><section className="materials-content"><Title subtitle="Upload official course material, PDFs, or photos of handwriting to automatically generate adaptives." action={<Button onClick={() => setUploaded(true)}>♧ &nbsp; Upload Material</Button>}>CS201 Study Materials</Title><div className="tabs">{['Materials', 'Past Papers', 'Scripts and Videos'].map((item) => <button type="button" className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>{uploaded && <p className="form-message">Upload queued. The parser is analyzing your new material.</p>}<section className="materials-list"><div className="table-head">RESOURCE NAME <span>PROCESSING STATUS</span><span>ACTIONS</span></div>{[['Intro_to_Computational_Complexity_LectureNotes.pdf', 'Processed'], ['Midterm_Preparation_PastQuestions_Oxford_2025.pdf', 'Analyzing this material...'], ['Draft_Revision_Syllabus_Outline.docx', 'Failed'], ['Turing_Machines_and_State_Hierarchy.pdf', 'Processed']].map(([name, status]) => <div className="material-row" key={name}><span>▣</span><strong>{name}<small>Added Aug 29, 2026</small></strong><Badge tone={status === 'Failed' ? 'red' : status.startsWith('Analyzing') ? 'dark' : 'green'}>{status}</Badge><Button kind="outline" onClick={() => setScreen('revision')}>{status === 'Failed' ? 'Retry Analysis' : 'View Sheets'}</Button><span>♧</span></div>)}</section></section></Page>; }
function App() { const [screen, setScreen] = useState('dashboard'); const screens = { dashboard: Dashboard, quiz: Quiz, exam: Exam, evaluation: Evaluation, diagnostics: Diagnostics, revision: Revision, admin: Admin, materials: Materials }; const Screen = screens[screen]; return <Screen setScreen={setScreen} />; }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
